services:
  userservice:
    build:
      context: ./UserService
    environment:
      - ASPNETCORE_URLS=https://0.0.0.0+:443;http://0.0.0.0+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345
      - ConnectionStrings__DefaultConnection=Server=UserDb;Database=UserServiceDb;User=UserService;Password=12345;
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${HOME}/.aspnet/https:/https:ro

  productservice:
    build:
      context: ./ProductService
    environment:
      - ASPNETCORE_URLS=https://0.0.0.0+:443;http://0.0.0.0+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345
      - ConnectionStrings__DefaultConnection=Server=localhost;Database=ProductServiceDb;User=ProductService;Password=12345;
    ports:
      - "5002:80"
      - "5003:443"
    volumes:
      - ${HOME}/.aspnet/https:/https:ro

  cartservice:
    build:
      context: ./CartService
    environment:
      - ASPNETCORE_URLS=https://0.0.0.0+:443;http://0.0.0.0+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345
    ports:
      - "5004:80"
      - "5005:443"
    volumes:
      - ${HOME}/.aspnet/https:/https:ro

  orderservice:
    build:
      context: ./OrderService
    environment:
      - ASPNETCORE_URLS=https://0.0.0.0+:443;http://0.0.0.0+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345
    ports:
      - "5006:80"
      - "5007:443"
    volumes:
      - ${HOME}/.aspnet/https:/https:ro

  paymentservice:
    build:
      context: ./PaymentService
    environment:
      - ASPNETCORE_URLS=https://0.0.0.0+:443;http://0.0.0.0+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345
    ports:
      - "5008:80"
      - "5009:443"
    volumes:
      - ${HOME}/.aspnet/https:/https:ro

  notificationservice:
    build:
      context: ./NotificationService
    environment:
      - ASPNETCORE_URLS=https://0.0.0.0+:443;http://0.0.0.0+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345
    ports:
      - "5010:80"
      - "5011:443"
    volumes:
      - ${HOME}/.aspnet/https:/https:ro

  apigateway:
    build:
      context: ./ApiGateway
    environment:
      - ASPNETCORE_URLS=https://0.0.0.0+:443;http://0.0.0.0+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345
    ports:
      - "5012:80"
      - "5013:443"
    volumes:
      - ${HOME}/.aspnet/https:/https:ro

  userdb:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: UserServiceDb
      MYSQL_USER: UserService
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3307:3306"
    volumes:
      - userdb-data:/var/lib/mysql

  productdb:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ProductServiceDb
      MYSQL_USER: ProductService
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3308:3306"
    volumes:
      - productdb-data:/var/lib/mysql

volumes:
  userdb-data:
    driver: local
  productdb-data:
    driver: local
