services:
  userservice:
    build:
      context: .
      dockerfile: ./UserService/Dockerfile
    depends_on:
      - userdb
    environment:
      - ASPNETCORE_URLS=https://0.0.0.0+:443;http://0.0.0.0+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345
      - ConnectionStrings__DefaultConnection=Server=userdb;Database=UserServiceDb;User=UserService;Password=12345;
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${HOME}/.aspnet/https:/https:ro

  productservice:
    build:
      context: .
      dockerfile: ./ProductService/Dockerfile
    depends_on:
      - productdb
    environment:
      - ASPNETCORE_URLS=https://0.0.0.0+:443;http://0.0.0.0+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345
      - ConnectionStrings__DefaultConnection=Server=productdb;Database=ProductServiceDb;User=ProductService;Password=12345;
    ports:
      - "5002:80"
      - "5003:443"
    volumes:
      - ${HOME}/.aspnet/https:/https:ro

  cartservice:
    build:
      context: .
      dockerfile: ./CartService/Dockerfile
    depends_on:
      - redis
    environment:
      - ASPNETCORE_URLS=https://0.0.0.0+:443;http://0.0.0.0+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345
      - Redis__ConnectionString=redis:6379
      - ProductService__BaseUrl=https://productservice:5003
    ports:
      - "5004:80"
      - "5005:443"
    volumes:
      - ${HOME}/.aspnet/https:/https:ro

  orderservice:
    build:
      context: .
      dockerfile: ./OrderService/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://0.0.0.0+:443;http://0.0.0.0+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345
    ports:
      - "5006:80"
      - "5007:443"
    volumes:
      - ${HOME}/.aspnet/https:/https:ro

  paymentservice:
    build:
      context: .
      dockerfile: ./PaymentService/Dockerfile
    depends_on:
      - paymentdb
    environment:
      - ASPNETCORE_URLS=https://0.0.0.0+:443;http://0.0.0.0+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345
      - ConnectionStrings__DefaultConnection=Server=paymentdb;Database=PaymentServiceDb;User=PaymentService;Password=12345;
    ports:
      - "5008:80"
      - "5009:443"
    volumes:
      - ${HOME}/.aspnet/https:/https:ro

  notificationservice:
    build:
      context: .
      dockerfile: ./NotificationService/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://0.0.0.0+:443;http://0.0.0.0+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345
      - ConnectionStrings__DefaultConnection=Server=notificationdb;Database=NotificationServiceDb;User=NotificationService;Password=12345;
    ports:
      - "5010:80"
      - "5011:443"
    volumes:
      - ${HOME}/.aspnet/https:/https:ro

  apigateway:
    build:
      context: .
      dockerfile: ./ApiGateway/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://0.0.0.0+:443;http://0.0.0.0+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345
    ports:
      - "5012:80"
      - "5013:443"
    volumes:
      - ${HOME}/.aspnet/https:/https:ro

  userdb:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: UserServiceDb
      MYSQL_USER: UserService
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3307:3306"
    volumes:
      - userdb-data:/var/lib/mysql

  productdb:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ProductServiceDb
      MYSQL_USER: ProductService
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3308:3306"
    volumes:
      - productdb-data:/var/lib/mysql

  paymentdb:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: PaymentServiceDb
      MYSQL_USER: PaymentService
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3309:3306"
    volumes:
      - paymentdb-data:/var/lib/mysql

  notificationdb:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: NotificationServiceDb
      MYSQL_USER: NotificationService
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3309:3306"
    volumes:
      - notificationdb-data:/var/lib/mysql

  redis:
    image: redis
    ports:
    - "6380:6379"


volumes:
  userdb-data:
    driver: local
  productdb-data:
    driver: local
  paymentdb-data:
    driver: local
  notificationdb-data:
    driver: local
